# Generated by Django 5.2.7 on 2025-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
