# Generated by Django 5.2.7 on 2025-12-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0003_profile_address_profile_contact_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
