# Generated by Django 5.2.7 on 2025-10-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0003_posting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
