# Generated by Django 5.2.7 on 2025-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0005_profile_academic_year_profile_bio_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
