# Generated by Django 5.2.7 on 2025-11-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('unverified', 'Unverified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
