# Generated by Django 5.2.7 on 2025-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogin', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('posting_approved', 'Posting Approved'), ('posting_rejected', 'Posting Rejected'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected')], max_length=50),
        ),
    ]
