# Generated by Django 5.2.7 on 2025-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_posting_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
