# Generated by Django 5.2.7 on 2025-12-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_posting_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]