# Generated by Django 5.2.7 on 2025-12-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_fix_team_name_null_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='team_name',
        ),
    ]
