# Generated by Django 5.2.7 on 2025-12-08 20:20

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_posting_team_name'),
    ]

    operations = [
        # Since the opportunity_type field already exists in the database,
        # we're just marking it as added in the migration history
        # without actually modifying the database schema
        migrations.RunSQL("", ""),  # Empty SQL operations
    ]