# Generated by Django 5.2.7 on 2025-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_add_opportunity_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='opportunity_type',
            field=models.CharField(choices=[('assistantship', 'Assistantship'), ('volunteer', 'Volunteer'), ('internship', 'Internship'), ('job', 'Job'), ('scholarship', 'Scholarship'), ('events', 'Events'), ('sports', 'Sports'), ('leadership', 'Leadership'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
