# Generated by Django 5.2.7 on 2025-12-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_fix_uses_supabase_storage_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_signed_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_supabase_path',
        ),
        migrations.RemoveField(
            model_name='application',
            name='signed_url_expires_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='uses_supabase_storage',
        ),
    ]
